### ISSUE TITLE
Can't find Kintex-7 FPGA - XC7K100T-FBG686

### ISSUE THREAD

**Issue by StefanL312** [antmicro/ddr5-tester#2]
Hello,

Thank you for your work and for sharing this project.

I am currently working on my master thesis regarding DRAM row hammering and am interested in using your DDR5-tester.

I have trouble finding the XC7K100T-FBG686 FPGA.

Could you advise me on this matter. Would you have possibly meant the 160 variant instead?

I am looking forward to your reply.

Kind regards,
Stefan

**Comment by pkatarzynski** [comment]
Hi Stefan - indeed there was a glitch in the MPN indicated in the README. I have already fixed that. The MPN for the FPGA should be XC7K160T-FBG676.  We are using XC7K160T-2FBG676C in the prototypes. The board can also be populated with 'FFG' version which is footprint-compatible.
